import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans_Thai } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'

const noto = Noto_Sans_Thai({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="th" suppressHydrationWarning>
      <body className={noto.className}><ThemeProvider attribute='class' defaultTheme='system' enableSystem>{children}</ThemeProvider></body>
    </html>
  )
}
