import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans_Thai } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import Providers from '@/components/Provider'
import { LandingNavbar } from '@/components/landing-navbar'
import { LandingFooter } from '@/components/landing-footer'

const noto = Noto_Sans_Thai({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Learncloud Quiz',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="th" suppressHydrationWarning>
      <body className={noto.className}>
        
        <Providers>
          <LandingNavbar />
          <div>{children}</div>
        </Providers>
        </body>
    </html>
  )
}
